# python-api-challenge
I think something went wrong with citipy in my WeatherPy program. Could be that my URL is wrong.
Each coordinate pair finds a city name very far away from the actual location, letting the coordinates in the dataframe pointing to nowhere. For example, the 'Rio Grande' coordinates point to Iran.
However, the rest of the program works just fine!